events {}

http {
    upstream api {
        server api1:8080;
        server api2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass         http://api;
            proxy_set_header   Host $host;
            proxy_set_header   X-User-ID $http_x_user_id;
        }
    }
}
